---
title: "TweetSentiments"
author: "Jean-Carlos Paredes"
date: "5/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(streamR)
library(sentiment)
library(ggplot2)

# tweet_txt <-subset(tweets.df, select = "text")
# tweet_txt <-tweets.df$text

# gettxt("/Users/jc/Desktop/TwitterR/franceKy23.json")
# gettxt("/Users/jc/Desktop/TwitterR/franceKy24.json")
# gettxt("/Users/jc/Desktop/TwitterR/starbucksNyc29.json")

gettxt <- function(file){
  # parse the json file and save to a data frame called tweets.df. Simplify = FALSE ensures that we include      lat/lon information in that data frame.
  file.df <- parseTweets(file, simplify = FALSE)
  tweet_txt <-subset(file.df, select = "text")
  tweet_txt <-file.df$text
  # remove retweet entities
  tweet_txt = gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", tweet_txt)
  # remove at people
  tweet_txt = gsub("@\\w+", "", tweet_txt)
  # remove punctuation
  tweet_txt = gsub("[[:punct:]]", "", tweet_txt)
  # remove numbers
  tweet_txt = gsub("[[:digit:]]", "", tweet_txt)
  # remove html links
  tweet_txt = gsub("http\\w+", "", tweet_txt)
  # remove unnecessary spaces
  tweet_txt = gsub("[ \t]{2,}", "", tweet_txt)
  tweet_txt = gsub("^\\s+|\\s+$", "", tweet_txt)
  tweet_txt = gsub("[^0-9a-zA-Z ,./?><:;’~`!@#&*’]","", tweet_txt)

# Perform Sentiment Analysis
# classify emotion

classify(tweet_txt)
}

classify <- function(x){
class_emo = classify_emotion(x, algorithm='bayes', prior=1.0)
  
  # get emotion best fit
  emotion <- class_emo[,7]
  
  # substitute NA's by 'unknown'
  #emotion[is.na(emotion)] = 'unknown'
  
  # classify polarity
  class_pol = classify_polarity(x, algorithm='bayes')
  # get polarity best fit
  polarity = class_pol[,4]
  
  # Create data frame with the results and obtain some general statistics
  # data frame with results
  sent_df = data.frame(text=x, emotion=emotion,
                       polarity=polarity, stringsAsFactors=FALSE)
  sent_df <-  sent_df[complete.cases(sent_df),]
  # sort data frame
  sent_df = within(sent_df,
                   emotion <- factor(emotion, levels=names(sort(table(emotion), decreasing=TRUE))))
  

#saveRDS(sent_df, "/Users/jc/Desktop/TwitterR/em3t.rds")

# Let’s do some plots of the obtained results
# plot distribution of emotions
# ggplot(sent_df, aes(x=emotion)) +
# geom_bar(aes(y=..count.., fill=emotion)) +
# scale_fill_brewer(palette='Dark2') +
# labs(x='emotion categories', y='number of tweets') +
# ggtitle('Sentiment Analysis of Tweets\n(classification by emotion)') +
# theme(plot.title = element_text(size=12, face='bold'))

return(sent_df)
}

```


